version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
